language: android
android:
        components:
                - tools
                - platform-tools
                - build-tools-26.0.0
                - android-26
                - extra-android-m2repository
                - extra-google-m2repository
                - extra-android-support
                - extra-google-google_play_services
jdk:script:
        - ./gradlew :pitchupcore:build
before_install:
        - chmod +x gradlew
before_script:
        $ANDROID_HOME/tools/bin/sdkmanager --licenses
branches:
        only:
                - master
jdk:
        - oraclejdk8