language: android
android:
        components:
                - tools
                - platform-tools
                - build-tools-25.0.2
                - build-tools-26.0.0-rc2
                - android-25
                - extra-android-m2repository
                - extra-google-android-support
script:
        - ./gradlew :pitchupcore:build
before_install:
        - chmod +x gradlew
branches:
        only:
                - master
jdk:
        - oraclejdk8